togglz:
  features:
    TYPE_FEATURE:
      enabled: true
    NAMING_FEATURE:
      enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: PostgreSQL
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true